[general]
target_url = "https://en.wikipedia.org/wiki/HTTP_cookie"

[header_analysis]
enable = true

[header_analysis.sql_map]
enable = false
extra_url = ""
extra_params = ""

[subdomain]
enable = true
proxies_file = ""
search_type = "small" #

[telnet]
enable = true
ports = ["", "", ""]

[nmap]
enable = true
scan_type = []
ports = ["", "", ""]
