[general]
target_url = "google.com"

[header_analysis]
enable = true

[header_analysis.sql_map]
enable = false
extra_url = ""
extra_params = ""

[subdomain]
enable = true
proxies_file = ""
search_type = "demo"

[telnet]
enable = true
ports = "80"

[nmap]
enable = true
scan_type = "tcp"
ports = "80"
