[general]
target_url = "en.wikipedia.org"

[header_analysis]
enable = false

[header_analysis.sql_map]
enable = false
extra_url = ""
extra_params = ""

[subdomain]
enable = false
proxies_file = ""
search_type = "small" #

[telnet]
enable = true
ports = "78-80, 99"

[nmap]
enable = false
scan_type = []
ports = ["", "", ""]
